### ISSUE TITLE
[youtube classic] global font color and background color setting breaks youtube page rendering

### ISSUE THREAD

**Issue by mhwgoo** [adamlui/userscripts#107]
Hey @adamlui, since you are looking at the code recently, I wanted to bring back my first encounter with this userscript: I had a `stylesheet.css` in qutebrowser's config folder, with global color setting like this:
```css
* {
  font-family: "Hack" !important;
  background-color: #282828 !important;
  color: #dcdfe4;
}
```
which broke the rendering of youtube, so I took it out before, which means I couldn't enjoy the conformity of dimmer background and font color across all web pages. If you've noticed, my default dark mode background(without extra color settings mentioned, not only YouTube) is too dark, making the font look too bright, not very comfortable for my eyes especially during night time even with my monitor brightness level at 0. If it's not very inconvenient, some workarounds would help a lot and also make this project more compatible with customization oriented browsers like qutebrowser. Thanks!

Screenshot after setting dimmer global colors:
![Screenshot 2024-10-29 at 11 57 56](https://github.com/user-attachments/assets/c2205e85-9806-4387-abec-9262e1db401d)

**Comment by adamlui** [comment]
Ok @mhwgoo I will install the potential malware as flagged by Bitdefender to fix it

**Comment by adamlui** [comment]
I had to jump thru many hoops because winget simply doesn't work so I installed choco, now it is installing qutebrowser but taking ages

**Comment by adamlui** [comment]
![image](https://github.com/user-attachments/assets/b15843d4-59c7-4946-bd5a-b1c0bd3eb5d2)

The disinfection is making it slower I think

**Comment by adamlui** [comment]
![image](https://github.com/user-attachments/assets/766ff1d3-5bcf-48d5-a8aa-743ea90a2866)

It immediately quarantined the qutebrowser.exe so I can't use it

**Comment by adamlui** [comment]
Can you search for

```js
    waitForElm('head').then(() => document.head.append(fixesStyle));
```

and comment it out

```js
    //waitForElm('head').then(() => document.head.append(fixesStyle));
```

also very important, add a `;` in the blank line above it, so final revision is

```js
...
    /* Fix disappearing bar in masthead */
    #background.ytd-masthead {
      opacity: 1 !important;
    }`
    ;
    //waitForElm('head').then(() => document.head.append(fixesStyle));
...
```

then re-enable the global css and how's it look?

**Comment by mhwgoo** [comment]
I couldn't stand Microsoft Windows. Maybe try compiling from source? Definitely I can do that later at home.

**Comment by mhwgoo** [comment]
Got a workaround by:
```css
html, body {
  /* background-color in * will break youtube. */
  background-color: #282828;
  /* color in * will not take effect on youtube and youtube needs it. */
  color: #dcdfe4;
  --yt-spec-base-background: #282828; 
  --yt-spec-text-primary: #dcdfe4;
}
```
